// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package search

type SearchResult interface {
	IsSearchResult()
}

type Repository struct {
	Name string `json:"name"`
}

func (Repository) IsSearchResult() {}
